Changed type to N and added consistent read to true
aws/aws-database-encryption-sdk-dynamodb-java pull request #296
Opened 2023-07-29 13:29 UTC by LeeroyHannigan

- The comments wrongly state that sort key is of type (S), whereas it is type (N), updated the comment.
- Added strong consistency for the read, to ensure you retrieve the item directly after writing.

2023-08-01 00:42 UTC, lavaleri requested changes
Thanks for the PR @LeeroyHannigan!

Adding a consistent read to this example is a great update. In order to make it clear that we aren't trying to be prescriptive around whether one should or should not use consistent reads in general, I have suggested adding a comment alongside your change in the PR.

2023-08-01 00:42 UTC, lavaleri commented on Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/BasicPutGetExample.java
> +                .consistentRead(Boolean.TRUE)
```suggestion
                // In this example we configure a strongly consistent read
                // because we perform a read immediately after a write (for demonstrative purposes).
                // By default, reads are only eventually consistent.
                // Read our docs to determine which read consistency to use for your application:
                // https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.ReadConsistency.html
                .consistentRead(Boolean.TRUE)
```

2023-08-01 11:24 UTC, LeeroyHannigan commented
@lavaleri  thanks for that. I noticed other parts of the examples will require the same changes, not sure if you know of an easy way to implement it in all needed files?

2023-08-02 17:39 UTC, lavaleri commented
Thanks for the update! Our CI isn't set up currently to accept changes from forks, so I have pushed this change to a branch directly off of upstream (and closed this PR): https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/pull/298

It appears that there may be another permission issue affecting our CI right now that we will look into. We'll keep the changes in that PR scoped to just the simple example for now.

2023-08-02 17:39 UTC, closed without merging