feat: Merge changes from 3.1.2
aws/aws-database-encryption-sdk-dynamodb-java pull request #583
Opened 2023-11-14 19:15 UTC by ajewellamz

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-15 18:17 UTC, lavaleri requested changes

2023-11-15 18:17 UTC, lavaleri commented on Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/BeaconStylesSearchableEncryptionExample.java
> +    basket.add("strawberry");
Why was this change made?

2023-11-15 18:17 UTC, lavaleri commented on README.md
> +   implementation("software.amazon.cryptography:aws-database-encryption-sdk-dynamodb:3.1.1")
```suggestion
   implementation("software.amazon.cryptography:aws-database-encryption-sdk-dynamodb:3.1.2")
```

2023-11-15 18:17 UTC, lavaleri commented on README.md
> +      <version>3.1.1</version>
```suggestion
      <version>3.1.2</version>
```

2023-11-15 18:19 UTC, ajewellamz commented on Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/BeaconStylesSearchableEncryptionExample.java
> +    basket.add("strawberry");
Because we changed how things are stored.
Before, encrypted sets maintained their original order.
Now, encrypted sets come back sorted.

2023-11-15 18:31 UTC, lavaleri commented on Examples/runtimes/java/DynamoDbEncryption/src/main/java/software/amazon/cryptography/examples/searchableencryption/BeaconStylesSearchableEncryptionExample.java
> +    basket.add("strawberry");
But the order shouldn't semantically matter. If we get a failure in our example when the input set isn't in order, then we are doing something wrong in our example.

2023-11-15 18:47 UTC, lavaleri commented on project.properties
>  projectJavaVersion=3.1.0
We need to update this as well.

2023-11-15 19:07 UTC, lavaleri approved these changes
LGTM

2023-11-21 18:17 UTC, josecorella commented
closing in favor of https://github.com/aws/aws-database-encryption-sdk-dynamodb-java/pull/588

2023-11-21 18:17 UTC, closed without merging